name: CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 6 * * 1'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        dependencies:
          - lowest
          - highest
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ast

      - uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-
            ${{ runner.os }}-php-

      - uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - run: vendor/bin/phpunit --colors=always

  cs:
    runs-on: ubuntu-latest
    container:
      image: ngyuki/php-dev:7.4
    steps:
      - uses: actions/checkout@v2
      - run: php-cs-fixer fix --dry-run --diff --ansi -v

  phan:
    runs-on: ubuntu-latest
    container:
      image: ngyuki/php-dev:7.4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-
            ${{ runner.os }}-php-
      - run: composer install --prefer-dist --no-progress --no-suggest --ansi -o
      - run: phan --color --no-progress-bar
